# Generated by Django 4.1.6 on 2023-02-18 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_remove_invoice_currency'),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdetail',
            name='currency',
        ),
        migrations.DeleteModel(
            name='Currency',
        ),
    ]
