# Generated by Django 4.1.6 on 2023-02-07 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_productcategory_productunit_alter_productdetail_note_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Indonesian Rupiah', max_length=20)),
                ('code', models.CharField(help_text='IDR', max_length=3)),
            ],
            options={
                'verbose_name_plural': 'Currencies',
            },
        ),
        migrations.AddField(
            model_name='productdetail',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.currency'),
        ),
    ]
