# Generated by Django 4.1.6 on 2023-02-18 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_remove_invoice_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(choices=[('purchase', 'PURCHASE'), ('sale', 'SALE')], default='sale', max_length=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('draft', 'DRAFT'), ('ready', 'READY'), ('paid', 'PAID'), ('cancel', 'CANCEL')], default='draft', max_length=10),
        ),
    ]
